config/routes.rb
JavaMirror::Application.routes.draw do
  resources :jar_files, except: [:edit, :update] do
    resources :bundled_java_classes, only: [:show], shallow: true
  end

  root to: "homepage#index"
end

app/models/bundled_java_class.rb
# encoding: UTF-8

# Model představuje Java třídu, která je obsažena v některém
# z nahraných JAR souborů
#
# Jedná se o jednoduchou reprezentaci třídy, který obsahuje dostatek informací
# pro získání jejího class objectu, se kterým se dá pracovat dále.
class BundledJavaClass < ActiveRecord::Base
  # Odkaz na model JarFile
  belongs_to :jar_file

  # Validations
  validates :jar_file_id,
            presence: true

  # Scopes

  # Třídy, které jsou v určitém JAR souboru (pokud nemáme jeho instanci)
  scope :in_jar, ->(jar_file_id) { where(jar_file_id: jar_file_id) }

  # Třídy, které mají dané kanonické jméno (v rámci JAR souboru bude vždy jen jedna)
  scope :with_canonical_name, ->(canonical_name) { where(canonical_name: canonical_name) }

  # Instance třídy ClassReflector, která nám poskytuje informace o Java clas objectu
  def class_reflector
    @class_reflector ||= ClassReflector.from_bundled_java_class(self)
  end

  # Načtení JAR souboru do paměti (require), abychom mohli získavat class
  # objecty.
  def require_jar
    jar_file.require_jar
  end
end

app/models/jar_file.rb
class JarFile < ActiveRecord::Base
  mount_uploader :data, JarUploader

  # Associations
  has_many :bundled_java_classes

  # Validations
  validates :data, presence: true

  # Callbacks
  before_create :save_filename
  after_create :extract_classes

  def classes
    jar_reader.classes
  end

  def jar_reader
    @jar_reader ||= JarReader.new(data.current_path)
  end

  def require_jar
    jar_reader
  end


  protected

  def save_filename
    self.name = data.file.filename
  end

  def extract_classes
    jar_reader.each do |klass|
      bundled_java_classes.create(klass.to_hash)
    end
  end
end

app/controllers/application_controller.rb
# Všechny ostatní controllery v aplikaci jsou potomkem této třídy
# Zde se nastavují globální filtry (třeba přihlášení) atd.
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bundled_java_classes_controller.rb
# Tento jednoduchý controller vyhledá pouze vyhledá dle ID
# instanci třídy BundledJavaClass a zobrazí ji
class BundledJavaClassesController < ApplicationController
  # Zobrazení detailu třídy
  def show
    @bundled_java_class = BundledJavaClass.find(params[:id])
  end
end

app/controllers/homepage_controller.rb
# Controller nemusí nic vyhledávat - pouze zobrazuje uvítací
# stránku pro uživatele.
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/jar_files_controller.rb
# Controller zajišťující CRUD pro JAR soubory (model JarFile)
class JarFilesController < ApplicationController
  # Zobrazení výpisu všech nahraných souborů
  def index
    @jar_files = JarFile.all
  end

  # Zobrazení detailu souboru - data načte helper
  def show
  end

  # Formulář pro nahrání nového souboru - novou instanci vytváří automaticky
  # helper.
  def new
  end

  # Zobrazení formuláře pro editaci JAR souboru (možnost nahrát jiný JAR)
  def edit
  end

  # Create akce - vytoření vytvoření záznamu v databázi, nahrání souboru
  # Pokud se vše povede, ja uživatel přesměrován na detail nahraného
  # souboru. Pokud ne, tak se mu zobrazí formulář pro přidání znovu.
  def create
    if jar_file.save
      redirect_to jar_file, notice: 'JAR soubor byl v pořádku nahrán'
    else
      render action: "new"
    end
  end

  # Update akce - změna JAR souboru (nahrání nového)
  # Zatím nemá velký smysl, prože celý model JarFile obsahuje pouze jedno
  # podstatné pole - odkaz na nahraný soubor.
  def update
    if jar_file.update_attributes(params[:jar_file])
      redirect_to jar_file, notice: 'JAR soubor byl změněn'
    else
      render action: "edit"
    end
  end

  # Smazání JAR souboru
  # Po jeho smazání je uživatel přesměrován zpět na výpis všech JAR souborů
  def destroy
    jar_file.destroy

    redirect_to jar_files_url,
                notice: "JAR soubor byl smazán"
  end


  protected

  # Metoda buď načte JAR soubor z databáze, nebo vytvoření nové instance
  # Pokud není params[:id] prázdné, pokusíme se vyhledat záznam v DB podle tohoto ID
  # Jinak vytvoříme novou instanci s parametry z params[:jar_file] (mohou být i prázdné)
  def jar_file
    @jar_file ||= params[:id] ? JarFile.find(params[:id]) : JarFile.new(params[:jar_file])
  end

  # Z předchozí metody vyrobíme helper, který bude přístupný i ve view
  helper_method :jar_file
end

app/helpers/application_helper.rb
# Globální helpery přístupné pro celou aplikaci
module ApplicationHelper
end

app/helpers/bundled_java_classes_helper.rb
# Helpery pro view controlleru BundledJavaClassController
module BundledJavaClassesHelper
  # Zobrazení výpisu některé vlastnosti Java class objectu
  # Spoléháme se na to, že nám controller zapsal do instanční proměnné
  # @bundled_java_class instanci modelu BundledJavaClass
  # Z této instance používáme metodu class_reflector, která
  # vrací instanci ClassReflector - to je adaptér mezi JavaClass (třída JRuby)
  # naším view. Viz dokumentace ClassReflector
  #
  # === Parametry
  #
  #   <tt>feature</tt>: kterou metodu ClassReflectoru budeme používat
  #   <tt>title</tt>: zobrazený popisek
  #   <tt>features</tt>: [nepovinné] seznam již získaných vlastností, pokud nechceme
  #                        přímo volat metodu na reflectoru
  def feature_list(feature, title, features = nil)
    # Můžeme seznam "features" prředat jako parametr
    if features.nil?
      features = @bundled_java_class.class_reflector.send(feature)
    end

    # Pokud není seznam nil nebo prázdný
    if features.present?
      heading = content_tag :h3, title
      list = content_tag :ul do
        list_items = ""
        features.map do |field|
          list_items << content_tag(:li, field)
        end
        list_items.html_safe
      end

      heading + list
    end
  end

  # Vypsání rozhraní dané třídy společně s odkazy na jejich "dokumentaci"
  def interfaces_with_links
    @bundled_java_class.class_reflector.interfaces.map do |interface|
      link_to_class(interface.to_s)
    end
  end

  # Odkaz na detail třídy (pokud se jedná o třídu z daného JAR souboru)
  # Jinak se zobrazí pouze název třídy, který není obalen odkazem.
  def link_to_class(class_name)
    klass = BundledJavaClass.
        in_jar(@bundled_java_class.jar_file_id).
        with_canonical_name(class_name).
        first

    if klass
      link_to class_name, klass
    else
      class_name
    end
  end
end

app/views/bundled_java_classes/show.html.haml
%h2= @bundled_java_class.canonical_name

- if @bundled_java_class.class_reflector.superclass.present?
  %strong
    Rodič: #{link_to_class @bundled_java_class.class_reflector.superclass.to_s}

= feature_list :inner_classes, "Vnořené třídy"
= feature_list :interfaces, "Implementovaná rozhraní", interfaces_with_links
= feature_list :declared_fields, "Atributy"
= feature_list :constructors, "Konstruktory"
= feature_list :instance_methods, "Veřejné metody"
= feature_list :class_methods, "Veřejné třídní metody"
= feature_list :inherited_instance_methods, "Zděděné metody"
= feature_list :inherited_class_methods, "Zděděné třídní metody"

app/views/homepage/index.html.haml
%strong= link_to "JAR soubory", jar_files_path

app/views/jar_files/_form.html.haml
= form_for(jar_file, :multipart => true) do |f|
  .field
    = f.label :data
    %br/
    = f.file_field :data

  .actions
    = f.submit

app/views/jar_files/index.html.haml
%h1 Nahrané JAR soubory

%strong= link_to 'Nahrát nový JAR', new_jar_file_path

%table
  %thead
    %tr
      %th JAR soubor
      %th Počet tříd
      %th{colspan: 2}

  %tbody
    - @jar_files.each do |jar_file|
      %tr
        %td= jar_file.name
        %td= jar_file.bundled_java_classes.size
        %td= link_to 'Zobrazit třídy', jar_file
        %td= link_to 'Smazat', jar_file, confirm: 'Are you sure?', method: :delete

app/views/jar_files/new.html.haml
%h1 Nahrání nového JAR souboru

= render 'form'

= link_to 'Back', jar_files_path

app/views/jar_files/show.html.haml
%p
  %b Name:
  = jar_file.name

%h3 Třídy v JAR
%ul
  - for klass in jar_file.bundled_java_classes
    %li
      %strong= link_to klass.canonical_name, klass

= link_to 'Zpět na výpis JAR souborů', jar_files_path

app/views/layouts/application.html.haml
!!!
%html
%head
  %title JavaMirror
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

= yield